### PR TITLE
Version 4

### PR DESCRIPTION
**Pull request by Sanyyouisf**
@ostrander-nathan
finish

### CODE REVIEW

**Comment by Sanyyouisf** [comment]
@drdreed
finish waiting to merge

**Comment by DevDreed** [comment]
image

When I am clicking on the more button it fills out the bottom songs but that should be dynamically injected into the DOM.  It keeps on adding a more button but no more songs are added.  Also when I delete it is not deleting the whole node.  The delete button is being left behind.

**Comment by DevDreed** [comment]
Also I am unable to delete the additional songs that were added by the more button.

**Comment by Sanyyouisf** [comment]
@drdreed
I guess i fix it now .

**Comment by Sanyyouisf** [comment]
@drdreed 
ready to merge

**Comment by DevDreed** [comment]
👍

**Pull request merged**
